### ISSUE TITLE
Recipe tries to download a libdbus non existent file

### ISSUE THREAD

**Issue by MagnaboscoL** [teamviewer/meta-teamviewer-iot-agent#2]
It seems that the recipe tries to download a non existent file `http://ftp.de.debian.org/debian/pool/main/d/dbus/libdbus-1-3_1.12.16-2_armhf.deb`. Since the file is not there the compilation fails.

I got the recipe working as expected simply modifying the line
`SRC_URI += "http://ftp.de.debian.org/debian/pool/main/d/dbus/libdbus-1-3_1.12.16-2_armhf.deb;md5sum=32fbba5e5571078171b815ff285ea0a2;sha256sum=e68cb7af028536db6149cd005c4178426a38fc6d0d707e299ea1251c86a5e141"`
to
`SRC_URI += "http://ftp.de.debian.org/debian/pool/main/d/dbus/libdbus-1-3_1.12.16-1_armhf.deb;md5sum=7b822af2e5807a54230b84598191d0c4;sha256sum=65c877f0c7555c51ab32ad2f43a6c5d4b70fe1e3a4b87ef270ddf287d6fb4385"`

The agent seems to work in my target but I am not sure that this is the proper solution.

**Comment by Nare** [comment]
Hi @MagnaboscoL . Thanks for notifying us about the problem. We will fix it ASAP.

**Comment by Nare** [comment]
Issue has been resolved.
