### ISSUE TITLE
libdbus debian package not found.

### ISSUE THREAD

**Issue by shantanoo-desai** [teamviewer/meta-teamviewer-iot-agent#4]
## Aim
Trying to port the `teamviewer-iot-agent` to i.MX6 Processor based Board from PHYTEC.

### Reproduction of Error

1. cloned the `master` branch initially
2. added to `conf/bblayers.conf` 
3. `bitbake -k teamviewer-iot-agent`

### ERROR
```
ERROR: teamviewer-iot-agent-1.0-r0 do_fetch: Fetcher failure for URL: 'http://ftp.de.debian.org/debian/pool/main/d/dbus/libdbus-1-3_1.12.16-1_armhf.deb;md5sum=7b822af2e5807a54230b84598191d0c4;sha256sum=65c877f0c7555c51ab32ad2f43a6c5d4b70fe1e3a4b87ef270ddf287d6fb4385'. Unable to fetch URL from any source.
ERROR: teamviewer-iot-agent-1.0-r0 do_fetch:
ERROR: teamviewer-iot-agent-1.0-r0 do_fetch: Function failed: base_do_fetch
```

I even tried `git checkout zeus` in the layer and I still get the same error. I am not sure what the solution for #4 was but it is not working.

**Comment by Nare** [comment]
Issue has been resolved. Thanks.
